export const templates = [
	"for {{ date_duration }}, he believed that {{ noun_actors }} were amazing",
	"the {{ noun_actors }} {{ verb_past }} to take it easy {{ date_duration }} ago",
	"{{ date_duration }} ago, they {{ verb_past }} and never came back",
	"the {{ noun_nonplural }} ran across the street {{ date_duration }} ago",
	"{{ date_duration }} ago, the {{ noun_nonplural }} ran across the street",
	"the organization, {{ noun_organization }} is known for its quality",
	"{{ noun }} is the best {{ noun }}",
	"{{ noun }} is the worst {{ noun }}",
	"being {{ a_noun_actors }} is awesome",
	"the {{ noun_demonyms }}s are said to be amazing people",
	"let's go to {{ noun_organization }}",
	"how marvelous it is to live another day",
	"it's very {{ adjective_latives }} to know the secret of one's friends",
	"{{ noun }} is the best {{ noun }}",
	"they {{ verb_past }} these things {{ date_duration }} ago",
	"a {{ verb_present_participle }} {{ noun }} is {{ an_adjective }} thing",
	"{{ noun }} is {{ an_adjective }} thing",
	"time is {{ verb_present_participle }}",
    "{{ noun_organization }} has been {{ verb_present_participle }} for {{ date_duration }} now",
    "she {{ verb_past }} at the {{ noun_oragnization }} {{ date_duration }} ago and never looked back",
    "{{ noun_demonyms }}s are known for their {{ adjective }} {{ noun }}",
    "{{ noun_organization }} provides {{ an_adjective }} {{ noun }} experience",
    "{{ noun_organization }}'s {{ noun }} is {{ an_adjective }} {{ noun }}",
    "{{ noun_oragnization }} is the best place to {{ verb }}",
    "{{ noun_nonplural }}s are {{ adjective }} at {{ verb }}",
    "she {{ verb_past }} the {{ noun_oragnization }} {{ date_duration }} ago and loved it",
    "the {{ noun_nonplural }}'s {{ noun }} is {{ an_adjective }} thing to witness",
    "{{ noun }} are {{ adjective }} and {{ adjective }}",
    "{{ noun }} is {{ an_adjective }} {{ noun }} to have",
    "he {{ verb_past }} his {{ noun }} and felt {{ adjective }} about it",
    "it's {{ an_adjective }} feeling to {{ verb }} with {{ noun_nonplural }}",
    "{{ noun_organization }}'s commitment to {{ noun }} is {{ an_adjective }} example",
    "{{ noun_oragnization }} is {{ an_adjective }} place to {{ verb }} with friends",
    "{{ noun_nonplural }} {{ verb_past }} at {{ noun_oragnization }} {{ date_duration }} ago",
	 "{{ noun }} is {{ an_adjective }} place to {{ verb }}",
    "{{ noun_organization }}'s dedication to {{ noun }} is truly {{ adjective }}",
    "the {{ noun_nonplural }} {{ verb_past }} through {{ noun_oragnization }} {{ date_duration }} ago",
    "for {{ date_duration }}, she {{ verb_past }} about {{ noun }}",
    "they {{ verb_past }} their {{ noun }}s {{ date_duration }} ago and never regretted it",
    "the {{ noun_nonplural }}'s {{ noun }} is {{ an_adjective }} experience",
    "{{ noun_organization }} is {{ an_adjective }} {{ noun }} to be part of",
    "{{ noun_oragnization }} is known for its {{ adjective }} {{ noun }}",
    "{{ noun_demonyms }}s are {{ adjective }} when it comes to {{ verb }}",
    "she {{ verb_past }} with {{ noun_nonplural }} at {{ noun_oragnization }} {{ date_duration }} ago",
    "{{ noun_organization }}'s {{ noun }} offers {{ an_adjective }} {{ noun }}",
    "{{ noun_nonplural }}s are {{ adjective }} {{ noun }}s",
    "he {{ verb_past }} his {{ noun }} {{ date_duration }} ago and never looked back",
    "it's {{ an_adjective }} feeling to {{ verb }} at {{ noun_oragnization }}",
    "{{ noun_demonyms }}s are {{ an_adjective }} group of people",
    "{{ noun }}s are known for their {{ adjective }} {{ noun }}",
    "she {{ verb_past }} with {{ noun_nonplural }} at {{ noun_oragnization }} and enjoyed it",
    "{{ noun_organization }}'s {{ noun }} is {{ an_adjective }} {{ noun }} to explore",
    "the {{ noun_nonplural }}'s {{ noun }}s {{ verb_past }} {{ date_duration }} ago",
]
